# Create a GitHub action to email a report from a file at 6 a.m. daily.
name: Send Report

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  send_report:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.PASSWORD }}
          subject: "Daily Report"
          body: "Please find the daily report attached."
          to: ${{ secrets.RECIPIENT }}
          attachments: "report.txt"